### ISSUE TITLE
D-geolib limits pile name length to 10 characters

### ISSUE THREAD

**Issue by Vincentvd-T** [Deltares/GEOLib#102]
We noticed that d-geolib limits the `pile_name` parameter length in classes like `TensionPileLocation` or `TensionRectangularPile` to 10 characters. Dfoundations it self does not seem to have this limit. Can this limit be removed or upgraded to atleast the dfoundations limit if there even is one?

**Comment by JohnBokma** [comment]
Hi Vincent, it is indeed true that D-Foundations itself  has no such limits, it just truncates the name for display purposes when needed. So I will look into this and if possible solve this for a next version.
