### ISSUE TITLE
DStability will not open geolib generated input files

### ISSUE THREAD

**Issue by breinbaas** [Deltares/GEOLib#122]
The current version of D-Stability (2023.01) generates an error with geolib generated stix files. The error is;

`Project could not be migrated to the latest version
Error converting value "MohrCoulombAdvanced to type`

**Comment by carloslubbers** [comment]
Which version of Geolib are you using? Could you supply the generated file and possibly the script that causes errors?

Geolib 1.0.0 supports 2023.01, older versions may not work correctly

**Comment by carloslubbers** [comment]
@breinbaas I think I fixed this in PR #124 in v1.0.1

**Comment by breinbaas** [comment]
I can confirm that it is fixed now, thx @carloslubbers !
