### ISSUE TITLE
DFoundations with new version

### ISSUE THREAD

**Issue by Nielszee92** [Deltares/GEOLib#128]
Previously when i ran my code with Version 0.2.0 there were no issues, now when i run my code with Version 1.0.1 i get the following problem:
ValueError: Got more fields than defined on model DFoundationsStructure:
                parser has {'calculation_warnings'} fields and
                model has set() fields not set.

**Comment by carloslubbers** [comment]
GEOLib was updated to support D-Foundations 2023.1 in version 0.6.0, what version of D-Foundations files and console are you using?

**Comment by Nielszee92** [comment]
Previously i worked with Geolib 0.2.0, the console had version 19.1. I am now using GeoLib v1.0.1 and downloaded the consoles through the download link provided on geolib docs. (even though the console there still says 19.1).

**Comment by carloslubbers** [comment]
I've contacted the maintainers of D-Foundations and it seems like the console download for D-Foundations is no longer required and will be removed from the download portal. You can copy all the installed files from the D-Foundations application to the GEOLib console directory, D-Foundatons 23.1 can be downloaded here: https://download.deltares.nl/geotechnical-software

**Comment by Nielszee92** [comment]
One more request @carloslubbers (since you are responding so quickly!), the download portal of the geotechnical software does not contain the common files which are required. Is it possible to ask the maintainers for this as well?

**Comment by carloslubbers** [comment]
Yes, they are hidden in the License Manager page right now, and we will display this more clearly! Our download portal got revamped recently and some pages need quite a bit of attention from us :)
https://download.deltares.nl/license-manager
