### ISSUE TITLE
Cannot execute DStability model

### ISSUE THREAD

**Issue by geodig** [Deltares/GEOLib#151]
I tried following the tutorial as given in https://deltares.github.io/GEOLib/latest/community/tutorial_dstability_general.html,
However, I always get the following error:

Error: Project could not be opened.
Error converting value "MohrCoulombAdvanced" to type 'Components.Persistence.Stability.Data.PersistableShearStrengthModelType'. Path 'Soils[0].ShearStrengthModelTypeAbovePhreaticLevel', line 10, position 77.
   at DGeoSuite.Components.Persistence.Archive.ArchiveSource.Read(ReadableEntity entity)
   at Components.Persistence.Stability.Archive.PersistableDataModelReader.ReadSoils()
   at Components.Persistence.Stability.Archive.PersistableDataModelReader.Read()
   at Application.Common.ProjectFileHelper.PersistableReader.Read(String filePath)
   at DGeoSuite.Components.Persistence.FilePersister.OpenFromFile[T](IPersistableReader`1 reader, String filePath)

I use d-geolib v1.3.3 and DStability version 2023.01
Any idea on what causes this error? I attached the generated stix file.
[geolib_trial.zip](https://github.com/Deltares/GEOLib/files/12762069/geolib_trial.zip)

**Comment by carloslubbers** [comment]
Hello, can you confirm to me that the Console version you are using in your geolib.env -> CONSOLES_FOLDER is also 2023.01? Installing D-Stability 2023.01 (the user interface) does not automatically update your GEOLib console. You can get the latest versions of the consoles from here: https://download.deltares.nl/geolib

**Comment by geodig** [comment]
Hi, how to check the console version? I downloaded it from https://download.deltares.nl/geolib at early this month, so I think it should be already 2023.01?

**Comment by carloslubbers** [comment]
You can check the file version of the D-Stability Console.exe file by checking its properties in Windows (right click file -> Properties -> Details)
![image](https://github.com/Deltares/GEOLib/assets/33954216/f72aa336-a41e-45f4-a61d-e7b6ed22c02a)

**Comment by carloslubbers** [comment]
I ran the attached notebook with a freshly downloaded copy of the console from our download portal and received a successful result, the error indicates you are still using a 2022.x based console, as it does not recognize the newly added Mohr Coulomb Advanced material model

**Comment by geodig** [comment]
Hi, yes I checked and it is indeed 2022 version. I will download the latest one then. Thanks
