### ISSUE TITLE
Parsing results of D-SheetPiling

### ISSUE THREAD

**Issue by Nielszee92** [Deltares/GEOLib#155]
I am now working on parsing results from D-Sheet Piling V23. However, the structure has changed since last time i used it. One big issue i have is that in the data the names of the phases are impossible to find. I would suggest to add the name of a phase to the results class, it's a small addition but for tracking results it's a big improvement. For now i would be helped a lot if you can point me to where i can find the stagenames in the serialized file.

**Comment by Nielszee92** [comment]
Thanks for the response! On my end the construction stages is a str, which makes it more difficulat to grab the staged constructions. It looks like this:
![afbeelding](https://github.com/Deltares/GEOLib/assets/63580963/145d5446-3fb8-4979-9d0d-4a2364b11083)

**Comment by zantDelta** [comment]
If you want to add the name of a phase to the results class, you can do it yourself. Please add a test for it and then make a pull request.

**Comment by zantDelta** [comment]
> Thanks for the response! On my end the construction stages is a str, which makes it more difficulat to grab the staged constructions. It looks like this: ![afbeelding](https://user-images.githubusercontent.com/63580963/274548319-145d5446-3fb8-4979-9d0d-4a2364b11083.png)

That is true. There is still a lot of work to do for better access. See the list in https://github.com/Deltares/GEOLib/issues/84.
