### ISSUE TITLE
Wrong waternet coordinate sequence in D-Stability

### ISSUE THREAD

**Issue by frisodam** [Deltares/GEOLib#157]
In some situations the waterline (or reference line) has a vertically oriented line segment. For instance a line with the following points: `(-200, 1), (0, 1), (0, 5), (200, 5)`. If I define a reference line in a D-Stability model with the method `add_reference_line`, the order of the points seems to be correct in the `DStabilityModel` instance. However, when serializing to a .stix file and opening this file, the points are swapped to `(-200, 1), (0, 5), (0, 1), (200, 5)`.

![image](https://github.com/Deltares/GEOLib/assets/140403298/e9bc3b7d-25a4-425c-bfc9-44bea88a9f4b)
![image](https://github.com/Deltares/GEOLib/assets/140403298/8e54a099-a76d-4e38-bc8c-b99ecd9dc3c4)

Is it possible to keep the order as defined in the .stix file? Thanks in advance.

**Comment by carloslubbers** [comment]
Hi Friso, this is currently a restriction of the data format in D-Stability. D-Stability will force points on a water line that are on the same vertical to run from the highest point to the lowest point, this can currently not change with geolib

**Comment by carloslubbers** [comment]
If you wish to work around this issue, you could opt to move the points to the side by a millimeter so they are no longer exactly above each other, that will allow you to use any order you want. Unfortunately that is a bit of an ugly workaround

**Comment by frisodam** [comment]
Thanks for your comment and suggestion, Carlos. I will implement the ugly workaround for now. It would be great to have this restriction removed in a future version of D-Stability.
