### ISSUE TITLE
allow dynamic settings for D-Stability console

### ISSUE THREAD

**Issue by MatthiasHauthDeltares** [Deltares/GEOLib#164]
As suggested in the [docs](https://deltares.github.io/GEOLib/latest/user/setup.html), I found it really helpful to set up the path of the DStability console in a dynamic way:

```python
dm.meta.console_folder = Path("other_location")  # has to exist!
```

However , this is no longer possible because the console path can no longer be set: 

```python
print(model.console_path)  # DStabilityConsole\D-Stability Console.exe
model.console_path = Path("other_location")  # crash :(
```

Note also that the meta attribute no longer exists too.

**Comment by carloslubbers** [comment]
@MatthiasHauthDeltares Would this PR help your case? https://github.com/Deltares/GEOLib/pull/165

**Comment by MatthiasHauthDeltares** [comment]
Thanks Carlos! I left a comment in your PR ;)
