### ISSUE TITLE
[DSheet] Missing feature for setting vertical balance parameters

### ISSUE THREAD

**Issue by KentropDevelopment** [Deltares/GEOLib#180]
There is no method for setting the maximum point resistance and xi factor that are needed for calculation the vertical balance. 

The current work-around is setting the vertical balance properties directly as a string via `model.datastructure.input_data.vertical_balance`.

I've created functionality for setting these parameters but I think I need to be assigned as a contributer in order to create a new branch. Could you add me as a contributer?

Regards,
Daniël Kentrop

![image](https://github.com/Deltares/GEOLib/assets/166102857/79f5c762-112a-48d0-8dc4-f9253c2c0fe2)

**Comment by wfaustmann** [comment]
Hi Daniël,

Good to hear that your want to make your first contribution. There is no need to add you as a contributor. By creating a pull request, you can create a branch yourself. When your commits are done, we will review the code and we merge the pull request upon approval.

Please let me know, if you have any questions.

Regards,
Walter

**Comment by KentropDevelopment** [comment]
Hi Walter,

Thanks for your explanation! I made a pull request #182 which fixes this issue. It is ready for review. Let me know if I should change or add anything. 

Regards,
Daniël
