### ISSUE TITLE
DStability input files with NaN values cannot be parsed

### ISSUE THREAD

**Issue by evetion** [Deltares/GEOLib#2]
*Originally reported by Thijs Damsma*

Somehow DStability files created with the desktop application can have NaN values for certain fields (I didn’t create them and don’t know exactly how this happened, but I do need to parse them). If one tries to load these in geolib these then the input is rejected as NaN is not a valid value for those fields. I’m guessing NaN should be interpreted as “not set”, so this can easily be solved by ignoring all fields with nan values when parsing the input.

**Comment by carloslubbers** [comment]
This should be fixed now in v0.1.9 by #26
