### ISSUE TITLE
D-Stability: parsing error with files generated from desktop

### ISSUE THREAD

**Issue by MatthiasHauthDeltares** [Deltares/GEOLib#25]
I generated an empty file from scratch (desktop D-Stability 2022.01.2) and tried to parse it with GEOLib. The default soils Id=2 and Id=11 can't be parsed properly and lead to pydantic ValidationErrors. I double-checked the variables and they are all positive in the .stix file so I am a bit puzzled by this error.

![errorGEOLIB](https://user-images.githubusercontent.com/113418841/192233568-7c376d08-126c-499b-8d8a-7c108f434a3b.PNG)

**Comment by yida-tao** [comment]
Hi, I am coming across the same error. In the preset materials 'Embankment Dry' and 'Dilantant Clay' there are NaN values for the Mohr-Coulomb and SHANSEP values. Also, there is a similar error when exporting stix from Riskeer. There, there are '-' values in the non-active material models.

**Comment by carloslubbers** [comment]
Will be fixed as part of https://github.com/Deltares/GEOLib/pull/26

**Comment by yida-tao** [comment]
Thanks a lot Carlos! :pray:

**Comment by carloslubbers** [comment]
This should be fixed now in v0.1.9 by #26
