### ISSUE TITLE
Path to DGeoFlow console

### ISSUE THREAD

**Issue by bartvanesWB** [Deltares/GEOLib#72]
There seems to be an minor mistake in the path to DGeoFlow console, which is not inline with an installed version of DGeoFlow. Using a geolib.env file and a MetaData class to set the path to the console, running DGeoFlow should be possible. However, the folder "DGeoFlowConsole" is not present after installing DGeoFlow.

geolib/models/dgeoflow/dgeoflow_model.py line 58 and 59:
```
    def console_path(self) -> Path:
        return Path("DGeoFlowConsole/DGeoFlow Console.exe")
```

Propose to change the path to return Path("DGeoFlow Console.exe")

**Comment by carloslubbers** [comment]
Hi! GEOLib expects all consoles to be put in a single folder currently according to a set structure, setting the console path in the env file to an installation directory will not work. 

Please refer to the Setup page on our documentation website for instructions regarding the folder structure:
https://deltares.github.io/GEOLib/latest/user/setup.html

> The geolib.env file is a simple text file, which can contain any number of parameters, for example:
> 
> CONSOLE_FOLDER="C:\\Users\\You\\Documents\\GEOLibConsoles"  # path has to exist!
> 
> This configuration variable points to the folder in which the consoles are placed (each in its own subfolder).
> 
> Note that the CONSOLE_FOLDER variable has to point to an existing path, otherwise GEOLib will not start. The executables are expected in the following locations:
> 
> - *CONSOLE_FOLDER*/"DFoundationsConsole/DFoundationsConsole.exe"
> - *CONSOLE_FOLDER*/"DSettlementConsole/DSettlementConsole.exe"
> - *CONSOLE_FOLDER*/"DSheetPilingConsole/DSheetPilingConsole.exe"
> - *CONSOLE_FOLDER*/"DStabilityConsole/D-Stability Console.exe"
> - *CONSOLE_FOLDER*/"DGeoFlowConsole/DGeoFlow Console.exe"
> 
> It can also be set by a CONSOLE_FOLDER environment variable. The enviroment variable will overrule the .env file, which in its turn, overrides the defaults set in Python.

You may need to copy the files from the D-Geo Flow installation directory to this new console folder.

We do think this should be a little more user friendly in the future as this part of the setup is a common pitfall with users

**Comment by bartvanesWB** [comment]
My bad, thanks for the clarification!
