### ISSUE TITLE
Markupsafe ImportError 'soft_unicode' when installing Geolib using pypi or requirements.txt

### ISSUE THREAD

**Issue by martijnkriebel** [Deltares/GEOLib#9]
Installing Geolib and its dependencies from either pypi (`pip install d-geolib`) or from Github directly results in an incorrect version of Markupsafe to be installed. Markupsafe v2.0.1 is specified in requirements.txt, but somehow v2.1.1 is installed. This results in the following error when importing Geolib:

```
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (c:\ProgramData\Anaconda3\envs\test5\lib\site-packages\markupsafe\__init__.py)
```

Apparently, [soft_unicode was removed in Markupsafe v2.1.0](https://github.com/aws/aws-sam-cli/issues/3661#issuecomment-1043965261), causing the ImportError.

Installation using the Poetry pyproject.toml file does result in v2.0.1 and therefore does not cause an error

**Comment by evetion** [comment]
Solved by #5
